export *  from "./home";
export * from "./home/contant_section";
export * from "./about";
export * from "./service";
export * from "./register";
export * from "./contactus";
export * from "./nft";
export * from "./physicalcoin";
export * from "./login";